[workspace]

members = [
  "days/day_1",
  "days/day_2",
  "days/day_3",
  "days/day_4",
  "days/day_5",
  "days/day_6",
  "days/day_7",
  "days/day_8",
  "days/day_9",
  "days/day_10",
  "days/day_11",
]

default-members = ["days/day_11"]
